In [4]:
from sklearn.metrics import roc_auc_score

In [5]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

In [6]:
X, y = load_breast_cancer(return_X_y=True)
clf = LogisticRegression(solver="liblinear").fit(X, y)
clf.classes_

array([0, 1])

In [13]:
y_score = clf.predict_proba(X)[:, 1]
X.shape, y.shape, y_score.shape

((569, 30), (569,), (569,))

In [8]:
roc_auc_score(y, clf.decision_function(X))

0.994767718408118

In [16]:
%timeit roc_auc_score(y, y_score**2)

1.26 ms ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [2]:
import torchmetrics
rocauc_torch = torchmetrics.AUROC(task='binary')

In [14]:
from torch import Tensor
y_ = Tensor(y)
y_score_ = Tensor(y_score)

In [17]:
%timeit rocauc_torch(y_score_, y_)

526 µs ± 23.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
y_score_.shape

torch.Size([569])

In [26]:
y_score_.unsqueeze(0).repeat(3,1)

tensor([[3.1652e-15, 2.0296e-08, 4.2894e-08,  ..., 1.8934e-03, 7.5279e-11,
         9.6320e-01],
        [3.1652e-15, 2.0296e-08, 4.2894e-08,  ..., 1.8934e-03, 7.5279e-11,
         9.6320e-01],
        [3.1652e-15, 2.0296e-08, 4.2894e-08,  ..., 1.8934e-03, 7.5279e-11,
         9.6320e-01]])

In [27]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,