In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [7]:
batch_size, n_classes = 10, 2
x = torch.randn(batch_size, n_classes)
x

tensor([[ 0.2332, -0.5394],
        [ 0.4342, -0.4918],
        [-1.0302, -0.7983],
        [ 1.0262, -1.2463],
        [ 1.0912, -0.0777],
        [-0.9625, -1.4372],
        [-0.8451, -0.3024],
        [ 1.0881, -0.9237],
        [-0.5808,  1.2503],
        [ 1.6646,  0.6226]])

In [8]:
target = torch.randint(n_classes, size=(batch_size,), dtype=torch.long)
y = torch.zeros(batch_size, n_classes)
y[range(y.shape[0]), target]=1
y

tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]])

In [9]:
def sigmoid(x): return (1 + (-x).exp()).reciprocal()
def binary_cross_entropy(pred, y): return -(pred.log()*y + (1-y)*(1-pred).log()).mean()

In [17]:
def softmax(x): return F.normalize(x.exp().reciprocal(), p=1.0)

In [18]:
softmax(x)

tensor([[0.3159, 0.6841],
        [0.2837, 0.7163],
        [0.5577, 0.4423],
        [0.0934, 0.9066],
        [0.2371, 0.7629],
        [0.3835, 0.6165],
        [0.6324, 0.3676],
        [0.1180, 0.8820],
        [0.8619, 0.1381],
        [0.2608, 0.7392]])

In [20]:
sigmoid(x), 1-sigmoid(x)

(tensor([[0.5580, 0.3683],
         [0.6069, 0.3795],
         [0.2631, 0.3104],
         [0.7362, 0.2233],
         [0.7486, 0.4806],
         [0.2764, 0.1920],
         [0.3005, 0.4250],
         [0.7480, 0.2842],
         [0.3587, 0.7774],
         [0.8409, 0.6508]]),
 tensor([[0.4420, 0.6317],
         [0.3931, 0.6205],
         [0.7369, 0.6896],
         [0.2638, 0.7767],
         [0.2514, 0.5194],
         [0.7236, 0.8080],
         [0.6995, 0.5750],
         [0.2520, 0.7158],
         [0.6413, 0.2226],
         [0.1591, 0.3492]]))